trigger:
- master

stages:
- stage: pr
  displayName: PR Validation
  jobs:
  - job: build_test
    displayName: 'Build and Test'
    pool:
      vmImage: 'macos-latest'
    steps:
    - task: Xcode@5
      displayName: 'Test'
      inputs:
        actions: 'test'
        configuration: 'Debug'
        sdk: 'iphonesimulator'
        scheme: 'BeastMatchTests'
        destinationPlatformOption: 'iOS'
        publishJUnitResults: true